
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhjcqtlewjnzeyfavnuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoamNxdGxld2puemV5ZmF2bnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODcyNDYsImV4cCI6MjA1OTI2MzI0Nn0.-6LabvHdflC-rkGgcCOiaf_ePpghbEnmL1Cci13QH7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
